name: Publish to GitHub Packages

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '24'
#          registry-url: 'https://npm.pkg.github.com/'

      - name: Setup npm for npmjs.org
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

#      - name: Publish to GitHub Packages
#        run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Publish to npmjs.com
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}